Update `rails' dependency version to 4.2.10
  `rails-api' dependency needs update to support rails >= 4.2.8:

    rake aborted!
    NoMethodError: undefined method `setup_generators!' for
    Scube::Application:Class
    /gems/railties-4.2.10/lib/rails/railtie.rb:196:in `method_missing'

  `rake' dependency needs ~> 10.5 version specifications, as rails 4.2
does not support rake 11:

    rake aborted!
    NoMethodError: undefined method `last_comment' for
    #<Rake::Application:0x0000000805825750>